title: CBS-LaTeX
email: plancomps@gmail.com
description: >-
  This site illustrates how CBS specifications of languages and funcons could be
  formatted for the web using LaTeX, Markdown, KaTeX, and MathJax.
  One of the aims is for CBS on web pages look like the CBS in published papers,
  using mathematical symbols instead of plain text.
baseurl: /cbs-latex
url: https://plancomps.github.io
github_username:  plancomps-admin

remote_theme: pdmosses/just-the-docs@combination-rec-nav
plugins:
  - jekyll-remote-theme
  
defaults:
  -
    scope:
      path: docs
      type: pages
    values:
      layout: default

aux_links:
  CBS-LaTeX on GitHub:
    - https://github.com/plancomps/cbs-latex

compress_html:
  blanklines: true

# Color scheme supports "dark", "light", and your custom schemes:
# color_scheme: nil                # default: light
# To add a button to switch all pages to a different scheme:
toggle_color_scheme: dark          # default: nil (no toggle button)
# To display the toggle button only on one page:
# toggle_page_url: "/"               # default: nil (display on all pages)
# To toggle automatically when the system mode preference changes:
# toggle_auto_mode: true             # default: nil (manual toggle)
# To set the button text for toggling and reverting:
# toggle_text_1: "&rarr; &#x26ab;" # default: "&rarr; Dark Mode"
# toggle_text_2: "&rarr; &#x26ab;" # default: "&rarr; Light Mode"

callouts:
  note:
    title: Note
    color: purple

nav_next_prev: true

exclude:
  - "*.aux"
  - "*.log"
  - "*.out"
