title: CBS-LaTeX
email: plancomps@gmail.com
description: >-
  This site illustrates how CBS specifications of languages and funcons could be
  formatted for the web using LaTeX, Markdown, KaTeX, and MathJax.
  One of the aims is for CBS on web pages look like the CBS in published papers,
  using mathematical symbols instead of plain text.
baseurl: "/cbs-latex"
url: "https://plancomps.github.io"
github_username:  plancomps-admin

remote_theme: pdmosses/just-the-docs@combination-rec-nav
plugins:
  - jekyll-remote-theme
  
defaults:
  -
    scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

aux_links:
  "CBS-LaTeX on GitHub":
    - "//github.com/plancomps/cbs-latex"

compress_html:
  blanklines: true

# color_scheme: light
auto_dark_scheme: dark

callouts:
  note:
    title: Note
    color: yellow

nav_next_prev: true

exclude:
  - "*.aux"
  - "*.log"
  - "*.out"
